language: android
android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-28.0.3                # Build tools version
    - android-28                        # Target SDK version
    - sys-img-armeabi-v7a-android-18    # Emulator

jdk: oraclejdk8

script:
  - cd android
  - ./gradlew build

env:
  - TERM=dumb

cache:
  directories:
    - $HOME/.gradle

branches:
  except:
    - gh-pages
    - assets

notifications:
  email: false
