name: CI
on:
    push:
        branches:
            - master
    pull_request:
jobs:
    build:
        name: Assemble
        runs-on: ubuntu-latest
        timeout-minutes: 25
        env:
            JAVA_TOOL_OPTIONS: -Xmx6g
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('/android/**/build.gradle') }}-${{ hashFiles('/android/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('/android/gradle/dependencies.gradle') }}

            - name: Assemble
              run: ./gradlew assemble
              working-directory: ./android              
    detekt:
        name: Detekt
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Detekt
              run: ./gradlew detekt
              working-directory: ./android
              
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 20
        env:
            JAVA_TOOL_OPTIONS: -Xmx4g
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Unit tests
              run: ./gradlew testDebugUnitTest
              working-directory: ./android

    instrumentation-tests:
        name: Instrumentation tests
        runs-on: macOS-latest
        timeout-minutes: 60
        env:
            JAVA_TOOL_OPTIONS: -Xmx4g
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
        strategy:
            matrix:
                api-level: [21,29]
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Instrumentation tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: ${{ matrix.api-level }}
                  arch: x86
                  script: ./android/gradlew connectedCheck -p android
