name: CI
on:
    push:
        branches:
            - master
    pull_request:
jobs:
    build:
        name: Assemble
        runs-on: ubuntu-latest
        timeout-minutes: 25
        env:
            JAVA_TOOL_OPTIONS: -Xmx6g
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.parallel=true
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/gradle/dependencies.gradle') }}

            - name: Assemble
              run: ./gradlew assemble
              working-directory: . 
    detekt:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        strategy:
          fail-fast: false
          matrix:
            compose-enabled: [ true,false ]
        name: Detekt [jetpack-compose-enabled=${{ matrix.compose-enabled }}]
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Detekt
              run: ./gradlew detekt -PuseCompose=${{ matrix.compose-enabled }} --stacktrace
              working-directory: .
              
    unit-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        env:
            JAVA_TOOL_OPTIONS: -Xmx4g
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.parallel=true
        strategy:
          fail-fast: false
          matrix:
            compose-enabled: [ true,false ]
        name: Unit tests [jetpack-compose-enabled=${{ matrix.compose-enabled }}]
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/gradle/dependencies.gradle') }}-${{ matrix.compose-enabled }}
            - name: Unit tests
              run: ./gradlew testDebugUnitTest -PuseCompose=${{ matrix.compose-enabled }}
              working-directory: .

    instrumentation-tests:
        runs-on: macOS-latest
        timeout-minutes: 60
        env:
            JAVA_TOOL_OPTIONS: -Xmx4g
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
        strategy:
            fail-fast: false
            matrix:
                api-level: [22,25,29]
                compose-enabled: [true,false]
                exclude:
                    - api-level: 22
                      compose-enabled: true
        name: Instrumentation tests [API=${{ matrix.api-level }}, jetpack-compose-enabled=${{ matrix.compose-enabled }}]
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - uses: actions/cache@v1
              with:
                 path: ~/.gradle/caches
                 key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/gradle/dependencies.gradle') }}-${{ matrix.compose-enabled }}


            - name: Instrumentation tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: ${{ matrix.api-level }}
                  arch: x86
                  script: ./gradlew connectedCheck -PuseCompose=${{ matrix.compose-enabled }}
